[project]
name = "devopsinterview"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pytz>=2025.2",
    "uvicorn[standard]>=0.35.0",
]
